### ISSUE TITLE
Sicherheitsfrage wird nicht angezeigt

### ISSUE THREAD

**Issue by Jaaaan** [contao/newsletter-bundle#10]
Beim Modul "Newsletter abonnieren" als auch "Newsletter kündigen" wird die Sicherheitsfrage nicht angezeigt, auch wenn diese nicht deaktiviert ist. Siehe https://demo.contao.org/en/newsletter.html

**Comment by xchs** [comment]
Siehe [Honeypot-Spamschutz](https://contao.org/de/news/contao_4-4-0.html)

**Comment by Jaaaan** [comment]
Stimmt, danke!
