### ISSUE TITLE
unsubscribe a newsletter with prefilled email

### ISSUE THREAD

**Issue by ghost** [contao/newsletter-bundle#12]
<a href="https://github.com/rustykowski"><img src="https://avatars0.githubusercontent.com/u/1775048?v=4" align="left" width="42" height="42"></img></a> [Issue](https://github.com/contao/core/issues/8835) by @rustykowski
December 29th, 2017, 16:25 GMT

Damit der Empfänger eines Newsletters diesen bequem abbestellen kann, möchte ich im E-Mail-Footer auf eine Seite verlinken, auf der das unsubscribe-Formular nur noch abgeschickt werden muss. Die betreffende E-Mail-Adresse sollte also bereits eingetragen sein.

Unter Contao 3.5 reichte es, den URL-Parameter "email" anzufügen, z.B `abbestellen.html?email=test@example.com`.
Unter Contao 4 reagiert das Modul leider nicht mehr auf diesen URL-Parameter. Woran liegt das?

**Comment by leofeyer** [comment]
Bist Du sicher, dass diese Funktion nicht von einer Erweiterung zur Verfügung gestellt wurde?

**Comment by rustykowski** [comment]
Ziemlich sicher. Auch kein Javascript. Siehe z.B:
https://www.uwehasubek.de/newsletter/abbestellen.html?email=test@example.com

**Comment by leofeyer** [comment]
In der 3.5 ist das Feature tatsächlich vorhanden:

https://github.com/contao/core/blob/3e41ad8718f6dea9c10c8a9b0341ed86f2bbe2ae/system/modules/newsletter/modules/ModuleUnsubscribe.php#L117

**Comment by aschempp** [comment]
Es wurde im Zusammenhang mit dem CAPTCHA entfernt, war wohl eher ein Unfall: https://github.com/contao/newsletter-bundle/commit/d145b7a6b4a035f55b0ef08b89f6adc916f661a7#diff-829b4c8677a795bebac9a20c8e610341L121

**Comment by leofeyer** [comment]
Behoben in c4829b8c4663c3b6e19809f9ad89d6da35c9a54d.

**Comment by Paddy0174** [comment]
Wird das in die LTS zurück portiert?
