### ISSUE TITLE
Newsletter unsubscribe

### ISSUE THREAD

**Issue by netzarbeiter** [contao/newsletter-bundle#22]
Until Contao 3.5 I used to add the following link to get the value in the form field to make the unsubscription easier.
https://demo.contao.org/en/newsletter.html?email=foo@example.com

You have readded this in Contao 4.5.0, can you please backport this change to Contao 4.4

https://github.com/contao/newsletter-bundle/commit/c4829b8c4663c3b6e19809f9ad89d6da35c9a54d

**Comment by leofeyer** [comment]
Backported in eccb9a4cf9d95f235ea4872d9b96b38a13d90a24.
