### ISSUE TITLE
Name of newsletter channel in breadcrumb navigation

### ISSUE THREAD

**Issue by Rigoperator** [contao/newsletter-bundle#23]
Sending newsletter: channel in breadcrumb navigation is not displayed correctly. Looks as if ID of newsletter is used instead of channel ID.
![contao_newsletter-channels](https://user-images.githubusercontent.com/4952864/43251609-a7db213e-90c0-11e8-9784-937147730704.jpg)

**Comment by leofeyer** [comment]
Fixed in contao/core-bundle@41c9ce42213b139c4a94d689c33a91437f8d2c45.
