### ISSUE TITLE
feature-request: Select members as newsletter-recipients

### ISSUE THREAD

**Issue by Ernestopheles** [contao/newsletter-bundle#29]
Quite often one wants to write to a selected set of members (select these from member list by filter or manually).
A new icon in a row in the member list would be fine, selecting these members for a special newsletter channel "write to selection".  And/or another button after clicking "process many" doing this job.

**Comment by xchs** [comment]
Unfortunately, you have created your issue in the wrong repository, as this is a read-only split repository:

![contao-newsletter-bundle](https://user-images.githubusercontent.com/1218766/92168714-03a75300-ee3b-11ea-8982-26f2726830fd.png)

Please go to https://github.com/contao/contao and create your issue there.
