### ISSUE TITLE
missing template "@ContaoCore/messages.html.twig"

### ISSUE THREAD

**Issue by fritzmg** [contao/newsletter-bundle#3]
There are two references for a `@ContaoCore/messages.html.twig` template in [`Contao\Newsletter`](https://github.com/contao/newsletter-bundle/blob/4.2.1/src/Resources/contao/classes/Newsletter.php). However, such a template does not seem to exist in the `core-bundle`, which results in an error when sending a newsletter:

```
Unable to find template "@ContaoCore/messages.html.twig" 
(looked into: …/vendor/contao/core-bundle/src/Resources/views).
```

**Comment by leofeyer** [comment]
Fixed in a27d960532fcd183af9e52b8d7a178e3ea7cddc2.
