### ISSUE TITLE
Problem sending Newsletter with variables

### ISSUE THREAD

**Issue by diversworld** [contao/newsletter-bundle#30]
Hi,

actually i found a problem that i cannot send a Newsletter anymore which contain variables  in combination with if query.

{if gender=="male"} Lieber ##firstname##, {elseif gender=="female"} Liebe ##firstname##, {else} Hallo, {endi}

Unexpected character "#" around position 7 for expression `gender&#61;&#61;&#34;male&#34;`.

I´m using the latest version:
Contao: 4.12.1

**Comment by Ernestopheles** [comment]
Das hatte ich gestern auch, es liegt an den Leerzeichen vor und hinter
den Operatoren, also wenn du von dem == und dahinter die Leerzeichen
entfernst, geht es wieder.
Offensichtlich schlägt neuerdings hier eine strengere Prüfung durch
(seit contao 4.12?)

Am Sonntag, dem 19.09.2021 um 00:13 -0700 schrieb Diversworld:

**Comment by Ernestopheles** [comment]
Gerade sehe ich, dass es bei dir vielleicht an etwas Anderem liegen könnte: `{endi}`

**Comment by diversworld** [comment]
Hallo Ernst,

danke für den Tipp. Das fehlende f beim endif ist nur ein Kopierfehler. 
Ich entferne gleich mal die Leerzeichfn.

Danke und viele Grüße 

Eckhard 

Von meinem iPhone gesendet

**Comment by diversworld** [comment]
Hallo ,

hat leider nicht geholfen:

{if gender=="male"}Lieber ##firstname##,{elseif gender=="female"}Liebe ##firstname##,{else}Hallo ##firstname##,{endif}

Der Fehler kommt trotzdem noch.

Unexpected character "#" around position 7 for expression `gender&#61;&#61;&#34;male&#34;`.

Viele Grüße 
Eckhard 

Von meinem iPhone gesendet

**Comment by Ernestopheles** [comment]
OK, dann weiß ich leider nicht.

Habe es bei mir gerade noch mal nachgestellt: Die Leerzeichen wieder
reingesetzt -> kein Fehler! Ist scheinbar nicht so leicht
reproduzierbar, es war aber definitv ausschlaggebend bei zwei meiner
Seiten.


Am Sonntag, dem 19.09.2021 um 05:37 -0700 schrieb Diversworld:

**Comment by diversworld** [comment]
Angemeckert werden die Zeichen == diese werden umgewandelt in &#63; das löst dann den Fehler aus.

**Comment by Ernestopheles** [comment]
Wie hast du das festgestellt und warum funktioniert es dann dennoch und wie wäre eine alternative Syntax?

**Comment by leofeyer** [comment]
Dieses Repo ist ein "Read-Only-Split" von https://github.com/contao/contao. Falls das Problem noch besteht, bitte öffne dort ein neues Issue: https://github.com/contao/contao/issues/new/choose
