### ISSUE TITLE
Double trailing slash after sendcycle

### ISSUE THREAD

**Issue by eiswurm** [contao/newsletter-bundle#32]
After a send cycle is over (in our case 10 emails per second) a reload takes place. In the URL there is a extra slash:

https://domain.tld//contao?do=newsletter&..........

In our case, this causes the 404 error page to load and the send is aborted. 

Contao version 5.0.7 / PHP 8.2 / nginx (Hostingwerk)

**Comment by de-es** [comment]
Duplicate see https://github.com/contao/contao/issues/5557

**Comment by leofeyer** [comment]
Thank you for your contribution.

Unfortunately, you have created your pull request in the wrong repository, as this is a read-only split repository. Please go to https://github.com/contao/contao and create your pull request there.
