### ISSUE TITLE
Newsletter dispatch should skip incorrect addresses

### ISSUE THREAD

**Issue by contaoacademy** [contao/newsletter-bundle#33]
The dispatch aborts completely with an error message if an incorrect address is included. (example: test@gmail.co)
It would helpful if the address is skipped and marked as incorrect.
The rest of the newsletter should continue.

`Expected response code "250/251/252" but got code "450", with message "450 4.1.2 <mitglied1@gmail.dof>: Recipient address rejected: Domain not found".`

**Comment by leofeyer** [comment]
Thank you for your contribution.

Unfortunately, you have created your issue in the wrong repository, as this is a read-only split repository. Please go to https://github.com/contao/contao and create your issue there.
