### ISSUE TITLE
Newsletter - Retry email and confirm receipt

### ISSUE THREAD

**Issue by jaceksynowiec** [contao/newsletter-bundle#5]
**Newsletter - Retry email and confirm receipt**
 
Once you have registered for the Newsletter, you will be sent a message asking for approval / Confirmation.
Is there an option to re-enable this message, manually or automatically (eg after some time)?
 
The problem is that not everyone will immediately click or forget to activate, and so would be more effective write.
 
**Innovative idea**
Manual resend button is required / Confirmation.

![](https://community.contao.org/pl/uploads/monthly_03_2017/post-262-0-10081000-1490625318.png)

**Comment by leofeyer** [comment]
I like the idea and I think we should also enable this for registration mails.

**Comment by jaceksynowiec** [comment]
OK

**Comment by leofeyer** [comment]
See contao/contao#196.
