### ISSUE TITLE
Modul Newsletter-Liste Fehler

### ISSUE THREAD

**Issue by jonnysp** [contao/newsletter-bundle#7]
bekomme seit der v4.4.3 
"Newsletter channels without redirect page cannot be used in a newsletter list at ..."
Weiterleitungsseite ist aber zugeordnet

muss an der letzen änderung liegen nach zurücksetzen der ModuleNewsletterList.php v4.4.2 geht es wieder bitte überprüfen. ( ich glaube es müssen nur die klammern wieder rein!)

https://github.com/contao/newsletter-bundle/blob/54750a5e624eebe93a1f292a4762fa9e01dcfb5d/src/Resources/contao/modules/ModuleNewsletterList.php#L85

```
if (!($objTarget = $objNewsletter->getRelated('pid')) instanceof NewsletterChannelModel)
```

**Comment by leofeyer** [comment]
Behoben in 226b22c69cdee899ec6ad74cfdfc56b4f17d7814. Danke @jonnysp.
